### ISSUE TITLE
No specimen.database module after successful build/install from git specimen-tools

### ISSUE THREAD

**Issue by phillipstanleymarbell** [josepablocam/specimen-tools#5]
No specimen.database module after successful build/install from git specimen-tools:

````
% python scripts/build_db.py 
Traceback (most recent call last):
  File "scripts/build_db.py", line 27, in <module>
    from specimen.database import db as db_def
ImportError: No module named specimen.database
%
````

**Comment by josepablocam** [comment]
Mmm. This is quite odd. Below what I get when working with a fresh Python 2.7 docker container and install sqlite3 and the repo from scratch.

```
$ cat Dockerfile
FROM python:2.7

RUN apt-get update
RUN apt-get install sqlite3
RUN git clone https://github.com/josepablocam/specimen-tools.git ~/specimen-tools
RUN cd ~/specimen-tools; pip install -e .
ENTRYPOINT ["python"]
```
In the same directory, 
```
$ docker build -t specimen-repro .
$ docker run --interactive --tty --rm specimen-repro\
      -c 'from specimen.database import db as db_def; print db_def' 
```

When I run this, I get the expected output:
`<module 'specimen.database.db' from '/root/specimen-tools/specimen/database/db.py'>` showing that the module should have been correctly installed.

Couple of quick questions:
* Do you have this same experience if you use `pip install specimen-tools` (i.e installing from PyPI rather than from repository)?
* Is the pip used to install from the repository for Python 2.7?
   
* Is the python used to run the script `build_db.py` also 2.7?

Here are the versions I have in the container for reproduction:
```
$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
$ python --version
Python 2.7.14
```

**Comment by phillipstanleymarbell** [comment]
* `pip install specimen-tools` results in the same issue
*  both pip and python are 2.7

````
pip --version
pip 9.0.1 from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)
````
and
````
python --version
Python 2.7.10
````
Running `python -c 'from specimen.database import db as db_def; print db_def'`
results in
````
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "specimen/database/db.py", line 31, in <module>
    from queries import SpecimenQueries
  File "specimen/database/queries.py", line 24, in <module>
    import pandas as pd
ImportError: No module named pandas
````
I'll try this on a different system.

**Comment by josepablocam** [comment]
That's even more odd, since `pip install specimen-tools` and `pip install -e .` should both install additional requirements, which are specified in `setup.py` and include `pandas`.  Below partial output of `pip install` on a fresh container:
```
Collecting specimen-tools
  Downloading specimen_tools-0.1.4-py2-none-any.whl
Collecting numpy (from specimen-tools)
  Downloading numpy-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl (16.9MB)
Collecting colormath (from specimen-tools)
  Downloading colormath-3.0.0.tar.gz
Collecting pycountry (from specimen-tools)
  Downloading pycountry-17.9.23.tar.gz (9.2MB)
Collecting pandas (from specimen-tools)
  Downloading pandas-0.22.0-cp27-cp27mu-manylinux1_x86_64.whl (24.3MB)
```

**Comment by phillipstanleymarbell** [comment]
Ah, since I'm using MacPorts, the default macOS python in `/usr/bin/python` is not what I want, instead `/opt/local/bin/python2.7`. Having solved that issue however, I run into the following:
````
% /opt/local/bin/python2.7 build_db.py ../specimen-data/Datasets/ psmdb
Parsing files in directory ../specimen-data/Datasets/ 
Writing to SQLITE Database(psmdb) with buffer limit = 20000 and cache limit = 40000
Traceback (most recent call last):
  File "build_db.py", line 89, in <module>
    main(args.data_dir, args.db_name, args.buffer, args.cache)
  File "build_db.py", line 80, in main
    populate(db_name, data_dir, _buffer, cache)
  File "build_db.py", line 37, in populate
    db = db_def.Database(db_name, rectypes, bufferSize, cacheLimit)
  File "/private/tmp/specimen-tools/specimen/database/db.py", line 52, in __init__
    self.specimen_queries = SpecimenQueries(database_name=name)
TypeError: __init__() got an unexpected keyword argument 'database_name'
````
I believe the problem is in `specimen/database/db.py`, line 49.
